# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the rake db:seed (or created alongside the db with db:setup).
#
# Examples:
#
#   cities = City.create([{ :name => 'Chicago' }, { :name => 'Copenhagen' }])
#   Mayor.create(:name => 'Emanuel', :city => cities.first)
#

user1 = User.create!(:login => "elie", :password => "noune")
user2 = User.create!(:login => "asdf", :password => "asdfasdf")

quiz1 = Quiz.create!(:name => "Syllables Quiz")
Question.create!(:quiz => quiz1, :youtube_id => "d1rpSeU8dJE", :answer => "ah" )
Question.create!(:quiz => quiz1, :youtube_id => "E8WolIw0nHw", :answer => "bah")
Question.create!(:quiz => quiz1, :youtube_id => "8m1oH3mov6Q", :answer => "sah")
Question.create!(:quiz => quiz1, :youtube_id => "hvbZtKLMAhA", :answer => "dah")
Question.create!(:quiz => quiz1, :youtube_id => "nAHtUKzYhtU", :answer => "fah")
Question.create!(:quiz => quiz1, :youtube_id => "sMwPCXf_4Vc", :answer => "gah")
Question.create!(:quiz => quiz1, :youtube_id => "gWwrJlGEcXE", :answer => "hah")
Question.create!(:quiz => quiz1, :youtube_id => "_X7yqvFgUlU", :answer => "jan")
Question.create!(:quiz => quiz1, :youtube_id => "9VKdK0QaK-g", :answer => "kah")
Question.create!(:quiz => quiz1, :youtube_id => "eRf52BzkWRk", :answer => "lah")
Question.create!(:quiz => quiz1, :youtube_id => "XXjfNDGEE14", :answer => "mah")
Question.create!(:quiz => quiz1, :youtube_id => "ZfBn-6eBp1o", :answer => "nah")

Question.create!(:quiz => quiz1, :youtube_id => "Xc6ZB4mD98U", :answer => "eh" )
Question.create!(:quiz => quiz1, :youtube_id => "6JU5zgmVaj0", :answer => "beh")
Question.create!(:quiz => quiz1, :youtube_id => "4KYJ5bYYGy4", :answer => "seh")
Question.create!(:quiz => quiz1, :youtube_id => "rzepgulCXo8", :answer => "deh")
Question.create!(:quiz => quiz1, :youtube_id => "hVYepPFwIoc", :answer => "feh")
Question.create!(:quiz => quiz1, :youtube_id => "IePaCtJeXTE", :answer => "geh")
Question.create!(:quiz => quiz1, :youtube_id => "aivxmyaDSVQ", :answer => "heh")
Question.create!(:quiz => quiz1, :youtube_id => "6BVSVMtfm70", :answer => "jeh")
Question.create!(:quiz => quiz1, :youtube_id => "vyX2qf4l1hA", :answer => "keh")
Question.create!(:quiz => quiz1, :youtube_id => "O8ZTfPg3eeY", :answer => "leh")
Question.create!(:quiz => quiz1, :youtube_id => "QbTCWXV0xTY", :answer => "meh")
Question.create!(:quiz => quiz1, :youtube_id => "JyjoKGIxsQ0", :answer => "neh")

Question.create!(:quiz => quiz1, :youtube_id => "h8WyMB9aZGk", :answer => "ee" )
Question.create!(:quiz => quiz1, :youtube_id => "-97D5nSX6xM", :answer => "bee")
Question.create!(:quiz => quiz1, :youtube_id => "4JAdYFn9xAA", :answer => "see")
Question.create!(:quiz => quiz1, :youtube_id => "dqRT3q07BNI", :answer => "dee")
Question.create!(:quiz => quiz1, :youtube_id => "SzBnYII74eQ", :answer => "fee")
Question.create!(:quiz => quiz1, :youtube_id => "LwoO6v-S034", :answer => "gee")
Question.create!(:quiz => quiz1, :youtube_id => "ixq202Nm30s", :answer => "hee")
Question.create!(:quiz => quiz1, :youtube_id => "xDvUxM3ZVuQ", :answer => "jee")
Question.create!(:quiz => quiz1, :youtube_id => "-oomnB4ZaR8", :answer => "kee")
Question.create!(:quiz => quiz1, :youtube_id => "dIMbrSp68lU", :answer => "lee")
Question.create!(:quiz => quiz1, :youtube_id => "-HK6jMpnTOg", :answer => "mee")
Question.create!(:quiz => quiz1, :youtube_id => "1UZOT8BNlkY", :answer => "nee")

Question.create!(:quiz => quiz1, :youtube_id => "uH6mJA6CKxc", :answer => "oh" )
Question.create!(:quiz => quiz1, :youtube_id => "2NGeYXJiSmU", :answer => "boh")
Question.create!(:quiz => quiz1, :youtube_id => "bT5KXnKuOzY", :answer => "soh")
Question.create!(:quiz => quiz1, :youtube_id => "4WFg2zKTXlM", :answer => "doh")
Question.create!(:quiz => quiz1, :youtube_id => "RL0j4bHbPJc", :answer => "foh")
Question.create!(:quiz => quiz1, :youtube_id => "s4oL_ZTEohU", :answer => "goh")
Question.create!(:quiz => quiz1, :youtube_id => "jn6bIM2E3Co", :answer => "hoh")
Question.create!(:quiz => quiz1, :youtube_id => "_wShCkUoAnQ", :answer => "joh")
Question.create!(:quiz => quiz1, :youtube_id => "2FnHh8qFanE", :answer => "koh")
Question.create!(:quiz => quiz1, :youtube_id => "t5ZSjwjNByc", :answer => "loh")
Question.create!(:quiz => quiz1, :youtube_id => "z9HDQIyNrcM", :answer => "moh")
Question.create!(:quiz => quiz1, :youtube_id => "ku0yYvCBPak", :answer => "noh")

Question.create!(:quiz => quiz1, :youtube_id => "kVF_fF5qX-Y", :answer => "oo" )
Question.create!(:quiz => quiz1, :youtube_id => "8a7qpGkE4KU", :answer => "boo")
Question.create!(:quiz => quiz1, :youtube_id => "4bilOblLOAs", :answer => "soo")
Question.create!(:quiz => quiz1, :youtube_id => "FqsCW_LuwNE", :answer => "doo")
Question.create!(:quiz => quiz1, :youtube_id => "88oaXNSmrZQ", :answer => "foo")
Question.create!(:quiz => quiz1, :youtube_id => "LwG8Lf7NYao", :answer => "goo")
Question.create!(:quiz => quiz1, :youtube_id => "esrPr_rc0P0", :answer => "hoo")
Question.create!(:quiz => quiz1, :youtube_id => "ikqBQCrwjQk", :answer => "joo")
Question.create!(:quiz => quiz1, :youtube_id => "3oZgKPat66M", :answer => "koo")
Question.create!(:quiz => quiz1, :youtube_id => "B0fwAY7F9A4", :answer => "loo")
Question.create!(:quiz => quiz1, :youtube_id => "3_um2ywu-0o", :answer => "moo")
Question.create!(:quiz => quiz1, :youtube_id => "Vz7NMWb0e1w", :answer => "noo")

